2023-10-04 09:05:29 [1468312] [INFO] Starting gunicorn 21.2.0
2023-10-04 09:05:29 [1468312] [INFO] Listening at: http://0.0.0.0:5000 (1468312)
2023-10-04 09:05:29 [1468312] [INFO] Using worker: eventlet
2023-10-04 09:05:29 [1468317] [INFO] Booting worker with pid: 1468317
2023-10-04 09:05:29 [1468318] [INFO] Booting worker with pid: 1468318
2023-10-04 09:05:29 [1468319] [INFO] Booting worker with pid: 1468319
2023-10-04 09:05:29 [1468320] [INFO] Booting worker with pid: 1468320
2023-10-04 09:05:29 [1468321] [INFO] Booting worker with pid: 1468321
2023-10-04 09:06:10 [1468312] [INFO] Handling signal: int
2023-10-04 09:06:11 [1468321] [INFO] Worker exiting (pid: 1468321)
2023-10-04 09:06:11 [1468317] [INFO] Worker exiting (pid: 1468317)
2023-10-04 09:06:11 [1468319] [INFO] Worker exiting (pid: 1468319)
2023-10-04 09:06:11 [1468320] [INFO] Worker exiting (pid: 1468320)
2023-10-04 09:06:11 [1468318] [INFO] Worker exiting (pid: 1468318)
2023-10-04 09:06:12 [1468312] [INFO] Shutting down: Master
2023-10-04 09:39:09 [1485150] [INFO] Starting gunicorn 21.2.0
2023-10-04 09:39:09 [1485150] [INFO] Listening at: http://0.0.0.0:5000 (1485150)
2023-10-04 09:39:09 [1485150] [INFO] Using worker: eventlet
2023-10-04 09:39:09 [1485157] [INFO] Booting worker with pid: 1485157
2023-10-04 09:39:09 [1485159] [INFO] Booting worker with pid: 1485159
2023-10-04 09:39:09 [1485162] [INFO] Booting worker with pid: 1485162
2023-10-04 09:39:09 [1485164] [INFO] Booting worker with pid: 1485164
2023-10-04 09:39:09 [1485165] [INFO] Booting worker with pid: 1485165
2023-10-04 09:41:29 [1485150] [INFO] Handling signal: winch
2023-10-04 09:41:29 [1485150] [INFO] Handling signal: winch
2023-10-04 09:47:10 [1485150] [INFO] Handling signal: int
2023-10-04 09:47:10 [1485164] [INFO] Worker exiting (pid: 1485164)
2023-10-04 09:47:10 [1485165] [INFO] Worker exiting (pid: 1485165)
2023-10-04 09:47:11 [1485157] [INFO] Worker exiting (pid: 1485157)
2023-10-04 09:47:11 [1485159] [INFO] Worker exiting (pid: 1485159)
2023-10-04 09:47:11 [1485162] [INFO] Worker exiting (pid: 1485162)
2023-10-04 09:47:11 [1485150] [INFO] Shutting down: Master
2023-10-04 09:47:22 [1489737] [INFO] Starting gunicorn 21.2.0
2023-10-04 09:47:22 [1489737] [INFO] Listening at: http://0.0.0.0:5000 (1489737)
2023-10-04 09:47:22 [1489737] [INFO] Using worker: eventlet
2023-10-04 09:47:22 [1489738] [INFO] Booting worker with pid: 1489738
2023-10-04 09:47:22 [1489739] [INFO] Booting worker with pid: 1489739
2023-10-04 09:47:22 [1489740] [INFO] Booting worker with pid: 1489740
2023-10-04 09:47:22 [1489741] [INFO] Booting worker with pid: 1489741
2023-10-04 09:47:22 [1489745] [INFO] Booting worker with pid: 1489745
2023-10-04 09:47:25 [1489745] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/run.py", line 4, in <module>
    from core.controllers.teacher import bp as bp_teacher
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/core/controllers/teacher.py", line 3, in <module>
    from app.schemas.teacher import TeacherIn
ModuleNotFoundError: No module named 'app'
2023-10-04 09:47:25 [1489741] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/run.py", line 4, in <module>
    from core.controllers.teacher import bp as bp_teacher
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/core/controllers/teacher.py", line 3, in <module>
    from app.schemas.teacher import TeacherIn
ModuleNotFoundError: No module named 'app'
2023-10-04 09:47:25 [1489740] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/run.py", line 4, in <module>
    from core.controllers.teacher import bp as bp_teacher
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/core/controllers/teacher.py", line 3, in <module>
    from app.schemas.teacher import TeacherIn
ModuleNotFoundError: No module named 'app'
2023-10-04 09:47:25 [1489745] [INFO] Worker exiting (pid: 1489745)
2023-10-04 09:47:25 [1489741] [INFO] Worker exiting (pid: 1489741)
2023-10-04 09:47:25 [1489740] [INFO] Worker exiting (pid: 1489740)
2023-10-04 09:47:25 [1489739] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/run.py", line 4, in <module>
    from core.controllers.teacher import bp as bp_teacher
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/core/controllers/teacher.py", line 3, in <module>
    from app.schemas.teacher import TeacherIn
ModuleNotFoundError: No module named 'app'
2023-10-04 09:47:25 [1489739] [INFO] Worker exiting (pid: 1489739)
2023-10-04 09:47:25 [1489738] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/pyenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/run.py", line 4, in <module>
    from core.controllers.teacher import bp as bp_teacher
  File "/home/desarrollador2/Documents/personal/sonrisas-fuertes-back/core/controllers/teacher.py", line 3, in <module>
    from app.schemas.teacher import TeacherIn
ModuleNotFoundError: No module named 'app'
2023-10-04 09:47:25 [1489738] [INFO] Worker exiting (pid: 1489738)
2023-10-04 09:47:25 [1489737] [ERROR] Worker (pid:1489741) exited with code 3
2023-10-04 09:47:25 [1489737] [ERROR] Worker (pid:1489740) exited with code 3
2023-10-04 09:47:25 [1489737] [ERROR] Worker (pid:1489738) was sent SIGTERM!
2023-10-04 09:47:25 [1489737] [ERROR] Worker (pid:1489739) was sent SIGTERM!
2023-10-04 09:47:25 [1489737] [ERROR] Shutting down: Master
2023-10-04 09:47:25 [1489737] [ERROR] Reason: Worker failed to boot.
2023-10-04 09:47:58 [1490104] [INFO] Starting gunicorn 21.2.0
2023-10-04 09:47:58 [1490104] [INFO] Listening at: http://0.0.0.0:5000 (1490104)
2023-10-04 09:47:58 [1490104] [INFO] Using worker: eventlet
2023-10-04 09:47:58 [1490107] [INFO] Booting worker with pid: 1490107
2023-10-04 09:47:58 [1490108] [INFO] Booting worker with pid: 1490108
2023-10-04 09:47:58 [1490109] [INFO] Booting worker with pid: 1490109
2023-10-04 09:47:58 [1490110] [INFO] Booting worker with pid: 1490110
2023-10-04 09:47:58 [1490111] [INFO] Booting worker with pid: 1490111
2023-10-04 09:49:16 [1490104] [INFO] Handling signal: int
2023-10-04 09:49:16 [1490110] [INFO] Worker exiting (pid: 1490110)
2023-10-04 09:49:16 [1490107] [INFO] Worker exiting (pid: 1490107)
2023-10-04 09:49:16 [1490108] [INFO] Worker exiting (pid: 1490108)
2023-10-04 09:49:16 [1490111] [INFO] Worker exiting (pid: 1490111)
2023-10-04 09:49:16 [1490109] [INFO] Worker exiting (pid: 1490109)
2023-10-04 09:49:17 [1490104] [INFO] Shutting down: Master
